import { z } from "zod";

const seasonExportSchema = z.object({
    _exportId: z.string(),
    year: z.number(),
    status: z.string().nullable().optional(),
    gp_count: z.number().nullable().optional(),
    quali_laps: z.number().nullable().optional(),
    race_laps: z.number().nullable().optional(),
    predictions_locked: z.boolean().nullable().optional(),
    isCurrent: z.boolean().optional(),
    pointsSystem: z.array(z.object({
        position: z.number(),
        points: z.number(),
    })).optional(),
    engineSuppliers: z.array(z.object({
        _exportId: z.string(),
        name: z.string(),
        nationality: z.string().nullable().optional(),
        note: z.number(),
        investment_level: z.number().nullable().optional(),
    })),
    teams: z.array(z.object({
        _exportId: z.string(),
        name: z.string(),
        short_name: z.string().nullable().optional(),
        nationality: z.string().nullable().optional(),
        color_primary: z.string().nullable().optional(),
        color_secondary: z.string().nullable().optional(),
        team_principal: z.string().nullable().optional(),
        technical_director: z.string().nullable().optional(),
        engineer_level: z.number().nullable().optional(),
        engine_supplier_id: z.string().nullable().optional(),
        is_factory_team: z.boolean().nullable().optional(),
        shareholders: z.string().nullable().optional(),
        owner_investment: z.number().nullable().optional(),
        sponsor_investment: z.number().nullable().optional(),
        surperformance_bonus: z.number().nullable().optional(),
        title_sponsor: z.string().nullable().optional(),
        sponsor_duration: z.number().nullable().optional(),
        sponsor_objective: z.string().nullable().optional(),
        sponsor_objective_met: z.boolean().nullable().optional(),
    })),
    drivers: z.array(z.object({
        _exportId: z.string(),
        first_name: z.string().nullable().optional(),
        last_name: z.string(),
        nationality: z.string().nullable().optional(),
        birth_year: z.number().nullable().optional(),
        note: z.number(),
        potential_min: z.number().nullable().optional(),
        potential_max: z.number().nullable().optional(),
        potential_revealed: z.boolean().nullable().optional(),
        potential_final: z.number().nullable().optional(),
        team_id: z.string().nullable().optional(),
        years_in_team: z.number().nullable().optional(),
        is_first_driver: z.boolean().nullable().optional(),
        contract_years_remaining: z.number().nullable().optional(),
        is_rookie: z.boolean().nullable().optional(),
        is_retiring: z.boolean().nullable().optional(),
        world_titles: z.number().nullable().optional(),
        career_races: z.number().nullable().optional(),
        career_wins: z.number().nullable().optional(),
        career_poles: z.number().nullable().optional(),
        career_podiums: z.number().nullable().optional(),
        career_points: z.number().nullable().optional(),
    })),
    cars: z.array(z.object({
        team_id: z.string().nullable().optional(),
        motor: z.number(),
        aero: z.number(),
        chassis: z.number(),
        engine_change_penalty: z.boolean().nullable().optional(),
    })),
    calendar: z.array(z.object({
        _exportId: z.string(),
        circuit_id: z.string(),
        round_number: z.number(),
        status: z.string().nullable().optional(),
        weather: z.string().nullable().optional(),
        rain_probability: z.number().nullable().optional(),
        notable_events: z.string().nullable().optional(),
    })),
    qualifyingResults: z.array(z.object({
        race_id: z.string(),
        driver_id: z.string(),
        position: z.number(),
    })),
    raceResults: z.array(z.object({
        race_id: z.string(),
        driver_id: z.string(),
        grid_position: z.number(),
        finish_position: z.number().nullable().optional(),
        status: z.string().nullable().optional(),
        points: z.number().nullable().optional(),
        fastest_lap: z.boolean().nullable().optional(),
        dnf_lap: z.number().nullable().optional(),
        dnf_reason: z.string().nullable().optional(),
    })),
    standingsDrivers: z.array(z.object({
        after_round: z.number(),
        driver_id: z.string(),
        position: z.number(),
        points: z.number().nullable().optional(),
        wins: z.number().nullable().optional(),
        podiums: z.number().nullable().optional(),
        poles: z.number().nullable().optional(),
        fastest_laps: z.number().nullable().optional(),
        dnfs: z.number().nullable().optional(),
    })),
    standingsConstructors: z.array(z.object({
        after_round: z.number(),
        team_id: z.string(),
        position: z.number(),
        points: z.number().nullable().optional(),
        wins: z.number().nullable().optional(),
        podiums: z.number().nullable().optional(),
        poles: z.number().nullable().optional(),
    })),
    predictionsDrivers: z.array(z.object({
        driver_id: z.string(),
        predicted_position: z.number(),
        score: z.number().nullable().optional(),
    })),
    predictionsConstructors: z.array(z.object({
        team_id: z.string(),
        predicted_position: z.number(),
        score: z.number().nullable().optional(),
    })),
    news: z.array(z.object({
        headline: z.string(),
        content: z.string().nullable().optional(),
        news_type: z.string().nullable().optional(),
        importance: z.number().nullable().optional(),
        after_round: z.number().nullable().optional(),
        arc_id: z.string().nullable().optional(),
    })),
    transfers: z.array(z.object({
        driver_id: z.string(),
        from_team_id: z.string().nullable().optional(),
        to_team_id: z.string().nullable().optional(),
        transfer_type: z.string().nullable().optional(),
        effective_year: z.number(),
        contract_years: z.number().nullable().optional(),
        is_first_driver: z.boolean().nullable().optional(),
        arc_id: z.string().nullable().optional(),
    })),
});

export const universeExportSchema = z.object({
    version: z.literal("1.0"),
    exportDate: z.string(),
    universe: z.object({
        name: z.string().min(1),
        description: z.string().nullable().optional(),
        start_year: z.number(),
    }),
    pointsSystem: z.array(z.object({
        position: z.number(),
        points: z.number(),
    })),
    regulations: z.array(z.object({
        effective_year: z.number(),
        name: z.string().nullable().optional(),
        description: z.string().nullable().optional(),
        affects_aero: z.boolean().nullable().optional(),
        affects_chassis: z.boolean().nullable().optional(),
        affects_motor: z.boolean().nullable().optional(),
        reset_type: z.string().nullable().optional(),
    })),
    rookiePool: z.array(z.object({
        first_name: z.string().nullable().optional(),
        last_name: z.string(),
        nationality: z.string().nullable().optional(),
        birth_year: z.number().nullable().optional(),
        potential_min: z.number(),
        potential_max: z.number(),
        available_from_year: z.number().nullable().optional(),
        drafted: z.boolean().nullable().optional(),
        drafted_season_id: z.string().nullable().optional(),
        drafted_team_name: z.string().nullable().optional(),
    })),
    narrativeArcs: z.array(z.object({
        _exportId: z.string(),
        name: z.string(),
        description: z.string().nullable().optional(),
        arc_type: z.string().nullable().optional(),
        status: z.string().nullable().optional(),
        importance: z.number().nullable().optional(),
        related_driver_ids: z.array(z.string()).nullable().optional(),
        related_team_ids: z.array(z.string()).nullable().optional(),
        started_season_id: z.string().nullable().optional(),
        started_round: z.number().nullable().optional(),
        resolved_season_id: z.string().nullable().optional(),
        resolved_round: z.number().nullable().optional(),
        resolution_summary: z.string().nullable().optional(),
    })),
    historyChampions: z.array(z.object({
        year: z.number(),
        champion_driver_name: z.string().nullable().optional(),
        champion_driver_team: z.string().nullable().optional(),
        champion_driver_points: z.number().nullable().optional(),
        champion_team_name: z.string().nullable().optional(),
        champion_team_points: z.number().nullable().optional(),
        season_summary: z.string().nullable().optional(),
    })),
    seasons: z.array(seasonExportSchema),
});

export type UniverseExportData = z.infer<typeof universeExportSchema>;
